#Sana
# --- Vertex / GCP ---
GCP_PROJECT_ID = "researchconnect-scsu-474217"
VERTEX_REGION = "us-central1"
VERTEX_SEARCH_LOCATION = "global"
# IMPORTANT: this must be the Search App ID that belongs to the *474217* project
VERTEX_SEARCH_APP_ID = "scsu-researchconnect_1760750987796"

# (optional) path if you want Streamlit to read it too
GOOGLE_APPLICATION_CREDENTIALS = "C:\\keys\\gcp-credentials.json"

# --- Firebase (new project) ---
FIREBASE_API_KEY = "AIzaSyCTYtifbb1QJWi_5Hc9JW9Z9z_Qd1W-qcY"
FIREBASE_AUTH_DOMAIN = "researchconnect-scsu-474217.firebaseapp.com"
FIREBASE_PROJECT_ID = "researchconnect-scsu-474217"
FIREBASE_STORAGE_BUCKET = "researchconnect-scsu-474217.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID = "526731741445"
FIREBASE_APP_ID = "1:526731741445:web:88ff62275d03ded4180f6c"
FIREBASE_MEASUREMENT_ID = "G-E9L1J3G3R7"
FIREBASE_DATABASE_URL = "https://researchconnect-scsu-474217-default-rtdb.firebaseio.com"
